name: Build and Push to ACR
on:
    push:
        branches:
            - 'main'
jobs:
    build:
        name: 'Build and Push to ACR'
        runs-on: ubuntu-latest

        defaults:
            run: 
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Docker Login
              uses: azure/docker-login@v2
              with:
                login-server: waterdrop.azurecr.io
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}


            - run: |
                docker build . -f Dockerfile -t waterdrop.azurecr.io/nicegui-hello-world:latest
                docker push waterdrop.azurecr.io/nicegui-hello-world:latest

            # - name: Echo
            #   run: |
            #     echo "${{ secrets.ACR_URL }}" | sed 's/./& /g'
            #     echo "${{ secrets.REGISTRY_USERNAME }}" | sed 's/./& /g'
            #     echo "${{ secrets.REGISTRY_PASSWORD }}" | sed 's/./& /g'
            #     echo "${{ secrets.ACR_IMAGE_TAG }}" | sed 's/./& /g'

            # - name: Build and Push to ACR
            #   uses: docker/build-push-action@v2
            #   with:
            #     push: true
            #     tags: ${{ secrets.ACR_IMAGE_TAG }}
            #     file: Dockerfile
            #     secrets: |
            #         "username=${{ secrets.REGISTRY_USERNAME }}"
            #         "password=${{ secrets.REGISTRY_PASSWORD }}"